import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import path from "node:path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [{
		name: "embedded-worker",
		setup(build) {
			build.onResolve({ filter: /\?worker$/ }, args => ({
				path: path.resolve(args.resolveDir, args.path.replace(/\?worker$/, ".ts")),
				namespace: "embedded-worker",
			}));
			build.onLoad({ filter: /.*/, namespace: "embedded-worker" }, async args => {
				const worker = await esbuild.build({
					entryPoints: [args.path], bundle: true, write: false,
					format: "iife", platform: "browser", target: "es2018",
					minify: true, metafile: true,
				});
				return {
					contents: `export default ${JSON.stringify(worker.outputFiles[0].text)}`,
					loader: "js",
					watchFiles: Object.keys(worker.metafile.inputs).map(file => path.resolve(file)),
				};
			});
		},
	}],
});

if (prod) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
}
